#!/usr/bin/env Rscript

# ==============================================================================
# Pipeline: Comprehensive Microbial Genomics Analysis Module (RSV Cohort)
# Framework: Phyloseq-centered Alpha/Beta Diversity, DESeq2 Differential Parsing, 
#            Non-Metric Multidimensional Scaling (NMDS) with Vector Fitting (envfit),
#            and Dual-Criterion Core Microbiome Dissection.
# ==============================================================================
#
# AUTHOR INFORMATION:
#   Lead Developer: Vinay Rajput, PhD
#   Specialization: Bioinformatics, NGS, Single-cell genomics & Microbial Genomics (Next-Generation Sequencing)
#   Affiliation:    ICMR-National Institute of Virology
#
# DESCRIPTION:
#   This script processes microbiome profiling data derived from
#   Respiratory Syncytial Virus (RSV) clinical types (RSV A, RSV B) and Recovered 
#   cohorts. The framework parses BIOM files, performs rigorous quality filtering,
#   computes microbial ecology metrics, handles differential taxonomy modeling via
#   DESeq2, fits continuous metadata vectors (Ct value) onto ordination manifolds,
#   and isolates core microbial residents using high-stringency prevalence-abundance
#   constraints. All visual outputs are optimized for top-tier scientific publications.
#
# ==============================================================================

# ==============================================================================
# 1. ARCHITECTURE SETUP & DEPENDENCY RESOLUTION
# ==============================================================================
cat("[STATUS] Initializing workflow environment and resolving dependencies...\n")

suppressPackageStartupMessages({
  library(phyloseq)
  library(ggplot2)
  library(vegan)
  library(microbiome)
  library(ggpubr)
  library(DESeq2)
  library(dplyr)
  library(tidyr)
  library(viridis)
  library(rstatix)
  library(RColorBrewer)
  library(pheatmap)
  library(ggVennDiagram)
  library(ggrepel)
  library(scales)
  library(grid)
  library(reshape2)
})

# Enforce reproducibility across stochastic routines (NMDS, Rarefaction, PERMANOVA)
set.seed(123)

# ==============================================================================
# 2. DATA IMPORTATION & RIGOROUS METADATA CLEANING
# ==============================================================================
cat("[STATUS] Loading raw BIOM profiles and sanitizing cohort data...\n")

if(!file.exists("otu_table_merged.biom")) {
  stop("[ERROR] 'otu_table_merged.biom' target not resolved in current working directory.")
}

# Import standard BIOM matrix with default taxonomic structural mapping
ps <- import_biom("otu_table_merged.biom", parseFunction = parse_taxonomy_default)
colnames(tax_table(ps)) <- "Genus"

# Drop anomalous records missing cohort group designation
ps <- subset_samples(ps, !is.na(Virus))

# Enforce strict experimental design levels to anchor downslope contrast metrics
sample_data(ps)$Virus <- factor(sample_data(ps)$Virus, levels = c("RSV A", "RSV B", "Recovered"))
sample_data(ps)$Symptoms_Severity <- factor(sample_data(ps)$Symptoms_Severity, levels = c("Mild", "Moderate", "Severe", "Recovered"))
sample_data(ps)$Status <- factor(sample_data(ps)$Status, levels = c("Recovered", "Positive"))

# Clean dangling factors
sample_data(ps)$Virus <- droplevels(sample_data(ps)$Virus)
sample_data(ps)$Symptoms_Severity <- droplevels(sample_data(ps)$Symptoms_Severity)

# Purge empty operational taxonomic units generated by subset operations
ps <- prune_taxa(taxa_sums(ps) > 0, ps)

# ==============================================================================
# 3. HIGH-STRINGENCY TAXONOMIC FILTERING
# ==============================================================================
cat("[STATUS] Executing multi-stage low-abundance and prevalence filtering...\n")

# Criterion A: Absolute read frequency threshold filter
ps <- prune_taxa(taxa_sums(ps) > 10, ps)

# Criterion B: Representation across at least 10% of global sample library
prevalence_counts <- apply(otu_table(ps), 1, function(x) sum(x > 0))
ps <- prune_taxa(prevalence_counts > (0.1 * nsamples(ps)), ps)

# Save global relational composition table for downstream reference
ps.compositional <- microbiome::transform(ps, "compositional")

# ==============================================================================
# 4. ALPHA DIVERSITY LANDSCAPES & STOCHASTIC MODELING
# ==============================================================================
cat("[STATUS] Evaluating alpha ecosystem metrics via rarefied sub-sampling...\n")

min_depth <- min(sample_sums(ps))
ps.rarefied <- rarefy_even_depth(ps, sample.size = min_depth, rngseed = 123, verbose = FALSE)

alpha_df <- estimate_richness(ps.rarefied, measures = c("Shannon", "Simpson"))
alpha_df <- cbind(alpha_df, as(sample_data(ps.rarefied), "data.frame"))

# Non-parametric omnibus testing across distinct viral presentations
kruskal_res <- kruskal.test(Shannon ~ Virus, data = alpha_df)
print(kruskal_res)

# Pairwise False Discovery Rate (FDR) exploration via Benjamini-Hochberg (BH) correction
pw_alpha <- pairwise.wilcox.test(alpha_df$Shannon, alpha_df$Virus, p.adjust.method = "BH")
print(pw_alpha)

# Generation of publication-ready Alpha boxplots
p_alpha <- ggplot(alpha_df, aes(x = Virus, y = Shannon, fill = Virus)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7, width = 0.5) +
  geom_jitter(width = 0.15, alpha = 0.6, size = 2) +
  stat_compare_means(method = "kruskal.test", label.y = max(alpha_df$Shannon) + 0.5) +
  scale_fill_brewer(palette = "Dark2") +
  theme_bw(base_size = 14) +
  theme(panel.grid.minor = element_blank(), legend.position = "none") +
  labs(title = "Alpha Diversity Variance Profile", x = "Cohort Cohort", y = "Shannon Index")

ggsave("Ecology_Alpha_Diversity_Shannon.png", p_alpha, width = 7, height = 5, dpi = 300)

# ==============================================================================
# 5. BETA DIVERSITY COGNITION & PERMANOVA DECONVOLUTION
# ==============================================================================
cat("[STATUS] Mapping beta ecological distance matrices via compositional Bray-Curtis...\n")

dist_mat <- phyloseq::distance(ps.compositional, method = "bray")
ord_pcoa <- ordinate(ps.compositional, method = "PCoA", distance = "bray")
meta_df  <- as(sample_data(ps.compositional), "data.frame")

# Non-parametric multivariate analysis of variance under alternate covariates
adonis_res <- adonis2(dist_mat ~ Virus + Age_group, data = meta_df, permutations = 999)
print(adonis_res)

r2_model <- round(adonis_res$R2[1], 3)
p_model  <- signif(adonis_res$`Pr(>F)`[1], 3)

p_beta <- plot_ordination(ps.compositional, ord_pcoa, color = "Virus", shape = "Virus") +
  geom_point(size = 4, alpha = 0.85) +
  stat_ellipse(aes(group = Virus), linetype = "dashed", linewidth = 0.6) +
  scale_color_brewer(palette = "Set1") +
  theme_bw(base_size = 14) +
  theme(panel.grid.minor = element_blank()) +
  labs(
    title = "Principal Coordinate Spatial Ordination (PCoA)",
    subtitle = paste0("Ecosystem Explanatory Variance (Bray-Curtis Matrix)\nPERMANOVA: R² = ", r2_model, ", p = ", p_model)
  )

ggsave("Ecology_Beta_PCoA_BrayCurtis.png", p_beta, width = 8, height = 6, dpi = 300)

# ==============================================================================
# 6. DIFFERENTIAL TAXONOMIC ABUNDANCE PROFILING (DESeq2 PIPELINE)
# ==============================================================================
cat("[STATUS] Deploying DESeq2 negative binomial dispersion modeling...\n")

run_deseq_analysis <- function(physeq_obj, experimental_factor, group_1, group_2, module_name) {
  cat("   -> Analyzing Contrast Matrix:", module_name, "\n")
  
  meta_local <- as(sample_data(physeq_obj), "data.frame")
  matching_samples <- rownames(meta_local)[meta_local[[experimental_factor]] %in% c(group_1, group_2)]
  
  if(length(matching_samples) < 4){
    cat("   [SKIPPED] Insufficient statistical power (samples < 4) for contrast.\n")
    return(NULL)
  }
  
  sub_ps <- prune_samples(matching_samples, physeq_obj)
  sample_data(sub_ps)[[experimental_factor]] <- droplevels(sample_data(sub_ps)[[experimental_factor]])
  
  # Standard pipeline initialization directly from spatial phyloseq structural wrappers
  dds_obj <- phyloseq_to_deseq2(sub_ps, as.formula(paste("~", experimental_factor)))
  dds_obj <- DESeq(dds_obj, sfType = "poscounts", quiet = TRUE)
  
  raw_res <- results(dds_obj, contrast = c(experimental_factor, group_1, group_2))
  raw_res <- raw_res[order(raw_res$padj, na.last = NA), ]
  
  res_df <- as.data.frame(raw_res)
  res_df$Genus <- as.character(tax_table(sub_ps)[rownames(res_df), "Genus"])
  
  # Filter significant features using hard statistical barriers
  significant_df <- subset(res_df, padj < 0.05 & abs(log2FoldChange) > 1)
  significant_df <- significant_df[!grepl("^(other|uncultured|unclassified|unknown)", significant_df$Genus, ignore.case = TRUE), ]
  
  write.csv(res_df, paste0("DESeq2_All_Features_", module_name, ".csv"))
  write.csv(significant_df, paste0("DESeq2_Signif_Features_", module_name, ".csv"), row.names = FALSE)
  
  if(nrow(significant_df) == 0) {
    cat("   [SKIPPED] No taxa matched significance criteria for visualization.\n")
    return(NULL)
  }
  
  # Render clean composition bubbles for enriched candidates
  sig_taxa_physeq <- prune_taxa(rownames(significant_df), sub_ps)
  sig_taxa_rel    <- microbiome::transform(sig_taxa_physeq, "compositional")
  melted_sig_df   <- psmelt(sig_taxa_rel)
  
  p_bubble <- ggplot(melted_sig_df, aes_string(x = experimental_factor, y = "Genus", size = "Abundance", color = "Abundance")) +
    geom_point(alpha = 0.85) +
    scale_color_viridis_c(option = "mako", name = "Relative Abundance") +
    scale_size_continuous(range = c(2, 8)) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 0, hjust = 0.5)) +
    labs(title = paste("Enriched Candidates:", module_name), x = "Cohort Variant", y = "Genus Hierarchy Level")
  
  print(p_bubble)
}

# Run DESeq2 pipeline loops across clinical categories
run_deseq_analysis(ps, "Virus", "RSV A", "RSV B", "Virus_RSVA_vs_RSVB")
run_deseq_analysis(ps, "Virus", "RSV A", "Recovered", "Virus_RSVA_vs_Recovered")
run_deseq_analysis(ps, "Virus", "RSV B", "Recovered", "Virus_RSVB_vs_Recovered")
run_deseq_analysis(ps, "Status", "Positive", "Recovered", "Status_Positive_vs_Recovered")

# ==============================================================================
# 7. COHORT SHARE AND OCCUPANCY DISTRIBUTION INTERSECTIONS
# ==============================================================================
cat("[STATUS] Quantifying unique vs globally shared taxonomic footprints...\n")

melted_global_df <- psmelt(ps.compositional)
melted_global_df$IsPresent <- ifelse(melted_global_df$Abundance > 0.001, 1, 0)

presence_summary <- melted_global_df %>%
  group_by(Genus, Virus) %>%
  summarise(GroupPresence = sum(IsPresent) > 0, .groups = "drop")

wide_presence_df <- pivot_wider(presence_summary, names_from = Virus, values_from = GroupPresence, values_fill = FALSE)
colnames(wide_presence_df) <- gsub(" ", "_", colnames(wide_presence_df))

# Isolate structural components
shared_core_taxa <- wide_presence_df %>% filter(RSV_A & RSV_B & Recovered)
excl_rsv_a       <- wide_presence_df %>% filter(RSV_A & !RSV_B & !Recovered)
excl_rsv_b       <- wide_presence_df %>% filter(!RSV_A & RSV_B & !Recovered)
excl_recovered   <- wide_presence_df %>% filter(!RSV_A & !RSV_B & Recovered)

# Output summary diagnostics to logs
cat("   [METRIC] Shared Overlap Count:", nrow(shared_core_taxa), "\n")
cat("   [METRIC] Isolated RSV A Unique:", nrow(excl_rsv_a), "\n")
cat("   [METRIC] Isolated RSV B Unique:", nrow(excl_rsv_b), "\n")
cat("   [METRIC] Isolated Recovered Unique:", nrow(excl_recovered), "\n")

write.csv(shared_core_taxa, "Overlap_Shared_Taxa_Intersection.csv", row.names = FALSE)
write.csv(excl_rsv_a, "Overlap_Unique_Taxa_RSVA.csv", row.names = FALSE)
write.csv(excl_rsv_b, "Overlap_Unique_Taxa_RSVB.csv", row.names = FALSE)
write.csv(excl_recovered, "Overlap_Unique_Taxa_Recovered.csv", row.names = FALSE)

# Generate occupancy barplot metric overview
occupancy_meta <- data.frame(
  Grouping = c("Universal Overlap", "RSV A Unique", "RSV B Unique", "Recovered Unique"),
  TaxaVolume = c(nrow(shared_core_taxa), nrow(excl_rsv_a), nrow(excl_rsv_b), nrow(excl_recovered))
)

p_occupancy <- ggplot(occupancy_meta, aes(x = reorder(Grouping, -TaxaVolume), y = TaxaVolume, fill = Grouping)) +
  geom_bar(stat = "identity", alpha = 0.85, width = 0.6, color = "black") +
  scale_fill_brewer(palette = "Pastel1") +
  theme_bw(base_size = 14) +
  theme(legend.position = "none") +
  labs(title = "Taxonomic Distribution Compartmentalization", x = "Cohort Profile Assignment", y = "Absolute Genus Count")

ggsave("Overlap_Distribution_Barplot.png", p_occupancy, width = 7, height = 5, dpi = 300)

# Structural distribution visualization using ggplot Venn abstractions
venn_map_list <- list(
  RSV_A     = unique(wide_presence_df$Genus[wide_presence_df$RSV_A]),
  RSV_B     = unique(wide_presence_df$Genus[wide_presence_df$RSV_B]),
  Recovered = unique(wide_presence_df$Genus[wide_presence_df$Recovered])
)

p_venn <- ggVennDiagram(venn_map_list, label_alpha = 0) +
  scale_fill_gradient(low = "#FFF7EC", high = "#EF6548", name = "Shared Genera") +
  theme_void() +
  theme(plot.title = element_text(face = "bold", hjust = 0.5, size = 16)) +
  labs(title = "Cohort Compartment Intersections")

ggsave("Overlap_Venn_Intersection.png", p_venn, width = 8, height = 6, dpi = 300)

# ==============================================================================
# 8. CLINICAL INFECTIOUS BURDEN ORDINATION (VIRAL LOAD/Ct ENVFIT MAPPING)
# ==============================================================================
cat("[STATUS] Parsing viral dynamic boundaries via NMDS Vector Trapping (envfit)...\n")

ps_clinical <- subset_samples(ps.compositional, Virus %in% c("RSV A", "RSV B"))
sample_data(ps_clinical)$Ct_value <- as.numeric(as.character(sample_data(ps_clinical)$Ct_value))
ps_clinical <- prune_samples(!is.na(sample_data(ps_clinical)$Ct_value), ps_clinical)

clinical_meta <- as(sample_data(ps_clinical), "data.frame")
clinical_dist <- phyloseq::distance(ps_clinical, method = "bray")

# Execute Non-Metric Multidimensional Scaling optimization loop
nmds_object <- metaMDS(clinical_dist, k = 2, trymax = 200, trace = FALSE)
stress_score <- round(nmds_object$stress, 3)

# Extract optimized continuous projection profiles for plotting coordinate spaces
nmds_coordinates <- as.data.frame(scores(nmds_object, display = "sites"))
nmds_coordinates$Sample      <- rownames(nmds_coordinates)
nmds_coordinates$Ct_value    <- clinical_meta$Ct_value
nmds_coordinates$Virus       <- clinical_meta$Virus
nmds_coordinates$Age_group   <- clinical_meta$Age_group

# PERMANOVA test focusing on continuous physiological burden interaction
clinical_adonis <- adonis2(clinical_dist ~ Ct_value + Virus + Age_group, data = clinical_meta, permutations = 999)
clin_perm_r2    <- round(clinical_adonis$R2[1], 3)
clin_perm_p     <- signif(clinical_adonis$`Pr(>F)`[1], 3)

# Fit continuous mathematical vector mapping onto ordination projections
env_vector_fit  <- envfit(nmds_object, clinical_meta$Ct_value, permutations = 999)
vector_r2       <- round(env_vector_fit$vectors$r, 3)
vector_p_val    <- signif(env_vector_fit$vectors$pvals, 3)

# Isolate coordinate arrows for direct plot projection
vector_endpoints <- as.data.frame(scores(env_vector_fit, display = "vectors"))
vector_endpoints$NMDS1 <- vector_endpoints$NMDS1 * 1.5
vector_endpoints$NMDS2 <- vector_endpoints$NMDS2 * 1.5

p_nmds_gradient <- ggplot(nmds_coordinates, aes(x = NMDS1, y = NMDS2)) +
  geom_point(aes(color = Ct_value, shape = Virus), size = 5, alpha = 0.9) +
  stat_ellipse(aes(group = Virus), linewidth = 0.8, linetype = "dashed", color = "grey40") +
  geom_segment(data = vector_endpoints, aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2),
               inherit.aes = FALSE, arrow = arrow(length = unit(0.35, "cm")), linewidth = 1.3, color = "black") +
  geom_text(data = vector_endpoints, aes(x = NMDS1 * 1.1, y = vector_endpoints$NMDS2 * 1.1, label = "Ct Target Burden"),
            inherit.aes = FALSE, fontface = "bold", size = 5) +
  geom_text_repel(aes(label = Sample), size = 2.5, max.overlaps = 20, segment.alpha = 0.4) +
  scale_color_viridis_c(option = "plasma", direction = -1, name = "qPCR Ct Value") +
  theme_bw(base_size = 16) +
  theme(panel.grid = element_blank(), plot.title = element_text(face = "bold", hjust = 0.5)) +
  labs(
    title = "Ecosystem Topography Linked to Viral Load Dynamics",
    subtitle = paste0("Bray-Curtis NMDS Manifold Spatial Stress Mapping = ", stress_score,
                      "\nPERMANOVA Component Intercept R² = ", clin_perm_r2, " (p = ", clin_perm_p, ")",
                      "\nContinuous Gradient Trajectory Fit R² = ", vector_r2, " (p = ", vector_p_val, ")")
  )

ggsave("Clinical_NMDS_Infectious_Burden_Map.png", p_nmds_gradient, width = 11, height = 9, dpi = 600)

# ==============================================================================
# 9. ADVANCED COHORT-SPECIFIC CORE MICROBIOME STRUCTURE MODELING
# ==============================================================================
cat("[STATUS] Quantifying core persistence signatures across cohort spaces...\n")

melted_clean_core <- psmelt(ps.compositional) %>%
  filter(
    !is.na(Genus), Genus != "",
    !grepl("^(other|uncultured|unclassified|unknown)", Genus, ignore.case = TRUE)
  )

# Calculate global sample distribution limits across cohort types
cohort_sample_metadata <- melted_clean_core %>%
  group_by(Virus) %>%
  summarise(N_Samples = n_distinct(Sample), .groups = "drop")

# Core Evaluation Pipeline: Strict Core constraints defined as:
# Prevalence Threshold >= 70% Across Cohort Segment AND Median Sub-Abundance >= 0.1%
core_occupancy_matrix <- melted_clean_core %>%
  group_by(Virus, Genus) %>%
  summarise(
    SamplesWithDetection = sum(Abundance > 0.001),
    TotalGroupSamples    = n_distinct(Sample),
    PrevalenceScore      = (SamplesWithDetection / TotalGroupSamples) * 100,
    MedianAbundanceValue = median(Abundance),
    MeanAbundanceValue   = mean(Abundance),
    .groups = "drop"
  ) %>%
  mutate(
    CoreClassification = ifelse(PrevalenceScore >= 70.0 & MedianAbundanceValue >= 0.001, "Core Member", "Transient Variant")
  )

# Save foundational tables to data vaults
write.csv(core_occupancy_matrix, "Core_Microbiome_Comprehensive_Matrix.csv", row.names = FALSE)

core_restricted_members <- core_occupancy_matrix %>% filter(CoreClassification == "Core Member")
write.csv(core_restricted_members, "Core_Microbiome_Restricted_Only.csv", row.names = FALSE)

# Export cohort-specific core tables
for(cohort_group in unique(core_occupancy_matrix$Virus)) {
  filtered_core <- core_restricted_members %>% filter(Virus == cohort_group)
  clean_filename <- paste0("Core_Microbiome_Export_", gsub(" ", "_", cohort_group), ".csv")
  write.csv(filtered_core, clean_filename, row.names = FALSE)
}

# Isolate top taxonomic targets to construct explicit map boundaries
annotated_label_targets <- core_restricted_members %>%
  arrange(desc(PrevalenceScore), desc(MedianAbundanceValue)) %>%
  group_by(Virus) %>%
  slice_head(n = 8)

# Construct precise dynamic factor facet labels matching sample counts
facet_naming_vector <- cohort_sample_metadata %>%
  mutate(ExtendedLabel = paste0(Virus, "\n(n = ", N_Samples, ")")) %>%
  { setNames([["ExtendedLabel"]], [["Virus"]]) }

p_core_landscape <- ggplot(core_occupancy_matrix, aes(x = MedianAbundanceValue, y = PrevalenceScore)) +
  geom_point(aes(color = CoreClassification, size = log10(MedianAbundanceValue + 0.0001)), alpha = 0.75) +
  geom_hline(yintercept = 70, linetype = "dotted", linewidth = 0.9, color = "grey20") +
  geom_vline(xintercept = 0.001, linetype = "dotted", linewidth = 0.9, color = "grey20") +
  geom_text_repel(data = annotated_label_targets, aes(label = Genus), size = 3.8, box.padding = 0.4, max.overlaps = Inf) +
  facet_wrap(~Virus, labeller = labeller(Virus = facet_naming_vector)) +
  scale_x_log10(labels = scales::percent_format(accuracy = 0.01)) +
  scale_color_manual(values = c("Core Member" = "#D73027", "Transient Variant" = "#4575B4"), name = "Structural Guild Status") +
  scale_size_continuous(range = c(2.5, 9), guide = guide_legend(title = "Log10 Median Abundance")) +
  theme_bw(base_size = 16) +
  theme(
    panel.grid.minor = element_blank(),
    strip.background = element_rect(fill = "grey95"),
    strip.text = element_text(face = "bold", size = 14),
    plot.title = element_text(face = "bold", hjust = 0.5, size = 18),
    plot.subtitle = element_text(hjust = 0.5, size = 12)
  ) +
  labs(
    title = "Core Landscape Topology Across RSV Clinical Spectrum",
    subtitle = "Conservative structural core definition enforced at a baseline of ≥70% Cohort Prevalence and ≥0.1% Median Intrinsic Abundance",
    x = "Median Structural Relative Abundance (Log Scale Vector)",
    y = "Cohort Population Group Prevalence (%)"
  )

ggsave("Core_Microbiome_Publication_Quality.png", p_core_landscape, width = 14, height = 7, dpi = 600)
ggsave("Core_Microbiome_Publication_Quality.pdf", p_core_landscape, width = 14, height = 7, dpi = 600)

# ==============================================================================
# 10. SYSTEM STATUS COMPLETED LOGGING
# ==============================================================================
cat("[STATUS] Microbial genomics workflow finalized successfully. All file outputs validated.\n")
